# Generated by Django 2.2.1 on 2019-10-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
